config/routes.rb
Rails.application.routes.draw do
  root "boards#index"
  resources :boards

  get "/users/sign_up", to: "registrations#new" ,as: "sign_up"
  post "/users/register", to: "registrations#create", as: "register"

  get "/users/sign_in", to: "sessions#new", as: "sign_in"
  post "/users/login", to: "sessions#create", as: "login"
  delete "/users/sign_out", to: "sessions#destroy", as: "sign_out"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, confirmation: true
    validates :nickname, presence: true

    before_create :encrypt_password

		def self.login(user)
			pw = Digest::SHA1.hexdigest("a#{user[:password]}z")
			User.find_by(email: user[:email], password: pw)
    end


    private
    def encrypt_password
      self.password = Digest::SHA1.hexdigest("a#{self.password}z")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
		def index
		  @boards = Board.all
		end

		def new
		  @board = Board.new
		end

		def create
			@board = Board.new(params_board)
			
			if @board.save
			  redirect_to boards_path, notice: "新增看板成功"
			else
				render :new
			end
		end

		def edit
		  @board = Board.find_by(id: params[:id])
		end

		def update
			@board = Board.find_by(id: params[:id])
			
			if @board.update(params_board)
			  redirect_to boards_path, notice: "修改看板成功"
			else
				render :edit
			end
		end

		def destroy
			@board = Board.find_by(id: params[:id])
			
			@board.destroy if @board
			redirect_to boards_path ,notice: "刪除看板成功"
		end


		private
		def params_board
		  params.require(:board).permit(:title)
		end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
      @user = User.new
    end

    def create
      @user = User.new(params_user)

      if @user.save
        redirect_to root_path, notice: "註冊成功"
      else
        render :new
      end
    end

    private
    def params_user
      params.require(:user).permit(:email, :password, :password_confirmation, :nickname)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	  @user = User.new
	end

	def create
		if User.login(params[:user])
			session[:userprof] = params[:user][:email]
			redirect_to root_path, notice: "登入成功"
		else
			redirect_to sign_in_path, notice: "登入失敗"
		end
	end

	def destroy
		session[:userprof] = nil
		redirect_to root_path, notice: "已登出"
	end


	private
	def params_user
	  params.require(:user).permit(:email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		if session[:userprof].present?
			@user ||= User.find_by(email: session[:userprof])
		else
			nil
		end
	end
end

app/views/boards/edit.html.erb
<h1>修改看板</h1>

<%= link_to "返回列表", boards_path %>

<%= form_for(@board) do |form| %>
<%= form.label :title, "看板名稱" %>
<%= form.text_field :title %>

<%= form.submit %>
<% end %>

app/views/boards/index.html.erb
<h1>看板列表</h1>

<%= flash[:notice] %>

<%= link_to "新增看板", new_board_path %>

<table>
    <thead>
        <tr>
            <td>看板名稱</td>
        </tr>
    </thead>
    <tbody>
        <% @boards.each do |board| %>
        <tr>
            <td><%= board.title %></td>
            <td>
                <%= link_to "修改", edit_board_path(board) %>
                <%= link_to "刪除", board_path(board), method: "delete", data: { confirm: "確定要刪除嗎?" } %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/boards/new.html.erb
<h1>新增看板</h1>

<%= link_to "返回列表", boards_path %>

<%= form_for(@board) do |form| %>
<%= form.label :title, "看板名稱" %>
<%= form.text_field :title %>

<%= form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zcard3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flash" if flash[:notice] %>
    
  <main class="main-section">
    <%= yield %>
  </main>
    
  </body>
</html>

app/views/shared/_flash.html.erb
<p><%= flash[:notice] %></p>

app/views/shared/_navbar.html.erb
<nav>
    <ul>
        <li><%= link_to "首頁", root_path %></li>
        <li><%= link_to "看板列表", boards_path %></li>
    </ul>

    <ul>
        <% if session[:userprof].present? %>

          <li><%= current_user.nickname %></li>
          <li><%= link_to "登出", sign_out_path, method: "delete" %></li>

        <% else %>

          <li><%= link_to "註冊", sign_up_path %></li>
          <li><%= link_to "登入", sign_in_path %></li>

          <% end %>
    </ul>
</nav>